\input texinfo

@settitle Hirundine manual

@titlepage
@title Hirundine manual
@end titlepage

@contents

@include logos.texi

@node Top
@top @hir{}

This document describes @hirundine{} which is a library that
represents a @commonlisp{} program as @hir{}, i.e., a control-flow
graph consisting of @emph{instructions} and @emph{data}.

@menu
* Introduction:: Introduction
* Nodes:: Nodes of a @cfg{}
* Information:: Information-gathering functions
* Index:: Complete index.
@end menu

@include chap-introduction.texi
@include chap-cfg.texi
@include chap-information.texi

@node Index
@unnumbered Index

@printindex cp

@bye
