(cl:in-package #:common-boot-ast-evaluator)

(defun ast-to-cps (client ast)
  (let ((variable (gensym))
        (*host-names* (make-hash-table :test #'eq))
        (exit (gensym "EXIT")))
    `(lambda (client environment)
       (declare (ignorable client environment))
       (let ((,exit (lambda (&rest ,variable)
                      (declare (ignore ,variable))
                      ,(pop-stack-operation client))))
         ,(cps client ast exit)))))
